{
  "title": "Validation report for ogc.metacat.iso19115.19115-4 - 19115-4 WG draft",
  "bblockName": "19115-4 WG draft",
  "bblockId": "ogc.metacat.iso19115.19115-4",
  "generated": "2024-11-13T05:13:54.362569+00:00",
  "result": false,
  "items": [
    {
      "source": {
        "type": "EXAMPLE",
        "requireFail": false,
        "filename": "build/tests/metacat/iso19115/19115-4/example_1_1.json",
        "url": "https://ogcincubator.github.io/iso19115-json/build/tests/metacat/iso19115/19115-4/example_1_1.json",
        "exampleIndex": 1,
        "snippetIndex": 1,
        "language": "json"
      },
      "result": false,
      "sections": [
        {
          "name": "FILES",
          "title": "Files",
          "entries": [
            {
              "op": "jsonld-uplift",
              "isError": false,
              "message": "JSON-LD context is present - uplifting"
            }
          ]
        },
        {
          "name": "JSON_SCHEMA",
          "title": "JSON Schema",
          "entries": [
            {
              "exception": "JSONDecodeError",
              "line": 21,
              "col": 54,
              "isError": true,
              "message": "Error parsing JSON example: Expecting ',' delimiter: line 21 column 54 (char 1902) on or near line 21 column 54"
            }
          ]
        },
        {
          "name": "UNKNOWN",
          "title": "Unknown errors",
          "entries": [
            {
              "exception": "ParserError",
              "isError": true,
              "message": "Traceback (most recent call last):\n,  File \"/src/ogc/bblocks/validate.py\", line 184, in _validate_resource\n    result = validator.validate(filename, output_filename, report,\n,  File \"/src/ogc/bblocks/validation/rdf.py\", line 303, in validate\n    graph = self._load_graph(filename, output_filename, report, contents, base_uri, prefixes)\n,  File \"/src/ogc/bblocks/validation/rdf.py\", line 158, in _load_graph\n    json_doc = load_yaml(content=contents)\n,  File \"/venv/lib/python3.10/site-packages/ogc/na/util.py\", line 189, in load_yaml\n    return yaml.load(content, Loader=SafeYamlLoader if safe else YamlLoader)\n,  File \"/venv/lib/python3.10/site-packages/yaml/__init__.py\", line 81, in load\n    return loader.get_single_data()\n,  File \"/venv/lib/python3.10/site-packages/yaml/constructor.py\", line 49, in get_single_data\n    node = self.get_single_node()\n,  File \"yaml/_yaml.pyx\", line 673, in yaml._yaml.CParser.get_single_node\n,  File \"yaml/_yaml.pyx\", line 687, in yaml._yaml.CParser._compose_document\n,  File \"yaml/_yaml.pyx\", line 731, in yaml._yaml.CParser._compose_node\n,  File \"yaml/_yaml.pyx\", line 845, in yaml._yaml.CParser._compose_mapping_node\n,  File \"yaml/_yaml.pyx\", line 731, in yaml._yaml.CParser._compose_node\n,  File \"yaml/_yaml.pyx\", line 847, in yaml._yaml.CParser._compose_mapping_node\n,  File \"yaml/_yaml.pyx\", line 860, in yaml._yaml.CParser._parse_next_event\n,yaml.parser.ParserError: while parsing a flow mapping\n  in \"<unicode string>\", line 21, column 17\ndid not find expected ',' or '}'\n  in \"<unicode string>\", line 21, column 54\n"
            }
          ]
        }
      ]
    }
  ],
  "globalErrors": {},
  "counts": {
    "total": 1,
    "passed": 0,
    "failed": 1
  }
}