Validation report for ogc.metacat.iso19115.19115-4 - 19115-4 WG draft
Generated 2024-11-13T05:13:54.362036+00:00
=== Files ===
JSON-LD context is present - uplifting
=== End Files ===

=== JSON Schema ===

** Validation error **
Error parsing JSON example: Expecting ',' delimiter: line 21 column 54 (char 1902) on or near line 21 column 54
=== End JSON Schema ===

=== Unknown errors ===

** Validation error **
Traceback (most recent call last):
,  File "/src/ogc/bblocks/validate.py", line 184, in _validate_resource
    result = validator.validate(filename, output_filename, report,
,  File "/src/ogc/bblocks/validation/rdf.py", line 303, in validate
    graph = self._load_graph(filename, output_filename, report, contents, base_uri, prefixes)
,  File "/src/ogc/bblocks/validation/rdf.py", line 158, in _load_graph
    json_doc = load_yaml(content=contents)
,  File "/venv/lib/python3.10/site-packages/ogc/na/util.py", line 189, in load_yaml
    return yaml.load(content, Loader=SafeYamlLoader if safe else YamlLoader)
,  File "/venv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
,  File "/venv/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
,  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
,  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
,  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
,  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
,  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
,  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
,  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
,yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 21, column 17
did not find expected ',' or '}'
  in "<unicode string>", line 21, column 54

=== End Unknown errors ===

